### PR TITLE
Added tooltip help for parameters

### PR DESCRIPTION
**Pull request by jbednar**
I'd be happy to hear a better way to do this, because I don't like messing with HTML and CSS in our own code, but even more than that I want tooltips to work so that my notebooks aren't all cluttered with`help(obj)`.  The version in this PR seems to work:

image

but maybe someone knows a way to do it using ipywidgets' existing tooltips?  I didn't see a way for those to apply to an HTML element, and the only way we got our parameters lined up was in an HTML element.

I'm not too happy about the formatting, though that's presumably easy enough to change as CSS. 

Also, I'd like to put the class docstring as a tooltip for the Parameterized object's name, which I can easily do by adding `self.helptip(self.parameterized)` in the appropriate spot:

``` python
        widgets = [ipywidgets.HTML(self.tooltip_def +
            ('<div class="ttip"><b>{0}'+self.helptip(self.parameterized)+'</b>').format(self.parameterized.name)+"</div>")]
```

However, then I get a dump of a huge docstring, when all I wanted was the actual text defined in this Parmeterized class (i.e., "An example parameterized class" in this case):

image

Does anyone know how to get the bare docstring, not the jazzed-up version that has all the parameters tacked onto it?

### CODE REVIEW

**Comment by philippjfr** [comment]
Looks fine to me although the formatting can be improved a bit. I'll try to have a look at that soon. For now this looks good to merge.

**Comment by philippjfr** [comment]
One thing, should we have an option to disable the tooltips?

**Comment by jbednar** [comment]
I guess it wouldn't hurt; not much opinion either way.

**Comment by philippjfr** [comment]
Without trying them I can't say, if they have any chance of being annoying to a user who is familiar with the parameters, e.g. by obscuring the widgets themselves due to a stray mouse movement, I'd vote for adding it.

**Comment by jbednar** [comment]
Ok.  

As for the class docstring, as best I can tell the `__class_docstring_signature` method in param/parameterized.py is overriding `__doc__` with the expanded version, and thus I don't see any way to recover the original string.  Expanding the string is configurable globally, by setting `parameterized.docstring_signature=False` and `parameterized.docstring_describe_params=False`, but it doesn't seem possible to do it on a per-call basis.  

Some of paramnb needs to move into param anyway, and when we do that (and release param) I guess we can make the class store its original docstring somewhere...

**Comment by philippjfr** [comment]
> Some of paramnb needs to move into param anyway, and when we do that (and release param) I guess we can make the class store its original docstring somewhere...

Sounds good, alternatively it'd be nice if we could render the formatted version correctly.

**Comment by jbednar** [comment]
Well, the formatted version includes all the parameters, which in this case is redundant since they are all already on the web page, so I don't think I'd want that information duplicated.

**Comment by philippjfr** [comment]
> Well, the formatted version includes all the parameters, which in this case is redundant since they are all already on the web page, so I don't think I'd want that information duplicated.

True, the original docstring is probably sufficient.

**Pull request merged**
