### PR TITLE
Added Button parameter

### PR DESCRIPTION
**Pull request by jbednar**
More of a pseudo-Parameter than a true parameter, but allows on_click operations to be tied to a button press in a property sheet.

### CODE REVIEW

**Comment by philippjfr** [comment]
Looks good to me, particularly the documentation revisions. I guess we should also release paramnb next week then.

**Comment by jbednar** [comment]
Yes, we need to release,  but it is currently broken on py3 and I don't think the notebook is running the next cells properly. Check it out and see what you think. ..

**Comment by jbednar** [comment]
Updating has now been fixed in commit 013ed76; I think the py3 issue is the only blocker now.

**Comment by jbednar** [comment]
Python3 issues have been fixed in 725499d, though some of the fixes were awkward, and if anyone can see if any should be handled differently, please make a suggestion.

**Pull request merged**
