### PR TITLE
multi select

### PR DESCRIPTION
**Pull request by marqh**

### CODE REVIEW

**Comment by philippjfr** [comment]
Looks good. As we discussed the `_make_widget` method will have to be refactored at some point but I'm happy to merge this now.

**Comment by jbednar** [comment]
> Avoid bugs by automatically running your tests. Continuous integration can help catch bugs by running your tests automatically. Merge your code with confidence using one of our continuous integration providers.

Does that mean there's no testing on paramnb yet?

**Comment by jbednar** [comment]
I just checked, and no, there aren't tests yet.  I guess that's ok for now, and we can add them at least some basic tests as part of a separate project we're about to return to in the next week or so.

**Comment by philippjfr** [comment]
> I just checked, and no, there aren't tests yet. I guess that's ok for now, and we can add them at least some basic tests as part of a separate project we're about to return to in the next week or so.

We absolutely should but the major issue is that it's going to be very difficult to test the widgets in any meaningful way. Not only are they in the browser but they also require a live IPython kernel.

**Comment by jbednar** [comment]
Yes, that's tricky.  But we can at least validate that the file loads, I'd think.  Can't they be tested at least a little in an IPython, as opposed to Jupyter, session, i.e. instantiated in some way in IPython that doesn't require a browser?

**Comment by philippjfr** [comment]
True, even importing the module would be better than nothing. Having it instantiate widgets from various types of parameters also sounds sensible, so yes, there absolutely are things we can test easily. What we won't be able to test very well is to make sure that the callbacks actually set the parameters correctly depending on the user selection.

**Comment by jbednar** [comment]
I just tried instantiating an ipywidget in bare IPython, and it complained "The 'kernel' trait of a Comm instance must be a Kernel, but a value of type 'NoneType' (i.e. None) was specified.", so it may not even be possible to instantiate the underlying widget until the work on making kernels launchable in the background is done...

**Pull request merged**
